//! SQLi corpus cases. Field coverage: query + cookies + body (form/json).
//! Rules (paranoia): union-select 1, tautology-or 1, stacked-query 1,
//! time-based 1, tautology-and 2, quote-comment 2, cast-convert 3, hex-literal 3.

use crate::{Case, Expect, Field, Module};

pub static CASES: &[Case] = &[
    // ── malicious: one per rule ────────────────────────────────────────────────
    Case {
        id: "sqli-union-select-query",
        module: Module::Sqli,
        field: Field::Query { name: "id", value: "1 UNION SELECT username,password FROM users--" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["sqli-union-select"],
        desc: "classic UNION-based column extraction in a query parameter",
    },
    Case {
        id: "sqli-tautology-or-query",
        module: Module::Sqli,
        field: Field::Query { name: "q", value: "' OR '1'='1" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["sqli-tautology-or"],
        desc: "quoted OR tautology",
    },
    Case {
        id: "sqli-stacked-query-form",
        module: Module::Sqli,
        field: Field::FormBody("id=1; DROP TABLE users"),
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["sqli-stacked-query"],
        desc: "stacked DROP after a semicolon, in a form body",
    },
    Case {
        id: "sqli-time-based-json",
        module: Module::Sqli,
        field: Field::JsonBody(r#"{"id":"1 AND SLEEP(5)"}"#),
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["sqli-time-based"],
        desc: "time-based blind via SLEEP() in a JSON body",
    },
    Case {
        id: "sqli-tautology-and-query",
        module: Module::Sqli,
        field: Field::Query { name: "id", value: "1 AND 1=1" },
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["sqli-tautology-and"],
        desc: "numeric AND tautology (PL2)",
    },
    Case {
        id: "sqli-quote-comment-cookie",
        module: Module::Sqli,
        field: Field::Cookie("sid=admin'--"),
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["sqli-quote-comment"],
        desc: "quote followed by SQL comment marker, in a cookie",
    },
    Case {
        id: "sqli-cast-convert-query",
        module: Module::Sqli,
        field: Field::Query { name: "id", value: "CAST(username AS int)" },
        min_pl: 3,
        expect: Expect::Triggers,
        rules: &["sqli-cast-convert"],
        desc: "CAST() data exfiltration helper (Notice/PL3)",
    },
    Case {
        id: "sqli-hex-literal-query",
        module: Module::Sqli,
        field: Field::Query { name: "id", value: "0xdeadbeef12" },
        min_pl: 3,
        expect: Expect::Triggers,
        rules: &["sqli-hex-literal"],
        desc: "long hex literal used to encode a string (Notice/PL3)",
    },
    // ── benign / traps ─────────────────────────────────────────────────────────
    Case {
        id: "sqli-benign-select-word",
        module: Module::Sqli,
        field: Field::Query { name: "q", value: "the best select occasions" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "'select' as an English word, not a keyword sequence",
    },
    Case {
        id: "sqli-benign-price-filter",
        module: Module::Sqli,
        field: Field::Query { name: "filter", value: "price > 10" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "legitimate comparison filter",
    },
    Case {
        id: "sqli-benign-sort-desc",
        module: Module::Sqli,
        field: Field::Query { name: "sort", value: "created_at DESC" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "legitimate sort clause",
    },
    Case {
        id: "sqli-trap-or-phrase",
        module: Module::Sqli,
        field: Field::Query { name: "q", value: "shoes for men or women=adult" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "OR-tautology narrowing trap: 'word or word=word' must not fire",
    },
    Case {
        id: "sqli-trap-and-phrase",
        module: Module::Sqli,
        field: Field::Query { name: "q", value: "red and blue=mix" },
        min_pl: 2,
        expect: Expect::Clean,
        rules: &[],
        desc: "AND-tautology narrowing trap (PL2): 'word and word=word' must not fire",
    },
];
