//! XSS corpus cases. Field coverage: query + cookies + body.
//! Rules (paranoia): script-tag 1, javascript-proto 1, event-handler 1,
//! dangerous-tag 2, eval 2, document-cookie 2, vbscript-proto 3, data-html-uri 3,
//! innerhtml 3.

use crate::{Case, Expect, Field, Module};

pub static CASES: &[Case] = &[
    // ── malicious: one per rule ────────────────────────────────────────────────
    Case {
        id: "xss-script-tag-query",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "<script>alert(1)</script>" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["xss-script-tag"],
        desc: "inline <script> tag",
    },
    Case {
        id: "xss-javascript-proto-query",
        module: Module::Xss,
        field: Field::Query { name: "url", value: "javascript:alert(document.domain)" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["xss-javascript-proto"],
        desc: "javascript: protocol handler",
    },
    Case {
        id: "xss-event-handler-query",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "<img src=x onerror=alert(1)>" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["xss-event-handler"],
        desc: "inline onerror event handler",
    },
    Case {
        id: "xss-dangerous-tag-query",
        module: Module::Xss,
        field: Field::Query { name: "html", value: "<iframe src=about:blank></iframe>" },
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["xss-dangerous-tag"],
        desc: "<iframe> dangerous tag (Warning/PL2)",
    },
    Case {
        id: "xss-eval-cookie",
        module: Module::Xss,
        field: Field::Cookie("pref=eval(atob('YWxlcnQ='))"),
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["xss-eval"],
        desc: "eval() call in a cookie value (Warning/PL2)",
    },
    Case {
        id: "xss-document-cookie-query",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "x=document.cookie" },
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["xss-document-cookie"],
        desc: "document.cookie access (Warning/PL2)",
    },
    Case {
        id: "xss-vbscript-proto-query",
        module: Module::Xss,
        field: Field::Query { name: "url", value: "vbscript:msgbox(1)" },
        min_pl: 3,
        expect: Expect::Triggers,
        rules: &["xss-vbscript-proto"],
        desc: "vbscript: protocol handler (Notice/PL3)",
    },
    Case {
        id: "xss-data-html-uri-query",
        module: Module::Xss,
        field: Field::Query { name: "src", value: "data:text/html,hello" },
        min_pl: 3,
        expect: Expect::Triggers,
        rules: &["xss-data-html-uri"],
        desc: "data:text/html URI (Notice/PL3); plain text payload to isolate the rule",
    },
    Case {
        id: "xss-innerhtml-query",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "el.innerHTML=payload" },
        min_pl: 3,
        expect: Expect::Triggers,
        rules: &["xss-innerhtml"],
        desc: "innerHTML sink assignment (Notice/PL3)",
    },
    Case {
        id: "xss-js-sink-invocation-query",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "confirm.call(null,1)" },
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["xss-js-sink-invocation"],
        desc: "tag/handler-less sink call — gotestwaf xss-scripting (URL); recall gap, Fase 10b",
    },
    Case {
        id: "xss-js-sink-call-query",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "(alert)(1)" },
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["xss-js-sink-call"],
        desc: "parenthesized bare sink call — gotestwaf xss-scripting (URL); Fase 10b",
    },
    Case {
        id: "xss-event-handler-pointer-query",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "<div onauxclick=doStuff()>x</div>" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["xss-event-handler"],
        desc: "onauxclick handler (new in the handler list) — gotestwaf community-xss; Fase 10b",
    },
    Case {
        id: "xss-document-cookie-bracket-query",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "x=document[\"cookie\"]" },
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["xss-document-cookie"],
        desc: "bracket-notation document[\"cookie\"] access — gotestwaf community-xss; Fase 10b",
    },
    // ── Base64Flat harvest (Fase 10c) — recall-lock under §6 base64-decode ───────
    // Not a gotestwaf-tracked deferral; pins that the derived channel feeds XSS too.
    Case {
        id: "xss-script-tag-b64",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["xss-script-tag"],
        desc: "base64(`<script>alert(1)</script>`) — caught at 10c via base64-decode",
    },
    // ── WIRE GROUND-TRUTH (Fase 10c REOPEN, pcap bypass.txt line 1220) ──────────
    // EXACT bytes: JSON body, backslash-u escaped. serde unescapes to
    // `%3CsvG%2Fx=%22%3E%22%2FoNloaD=confirm%28%29%2F%2F`; ONE percent-decode would
    // give `<svG/x=">"/oNloaD=confirm()//` → xss-event-handler (onload). But the JSON
    // leaf reaches the modules RAW (no canonicalize_value on JSON values) → no decode →
    // BYPASS (probe score 0). STEP-1 ground-truth; STEP 2 canonicalizes JSON leaves.
    Case {
        id: "xss-wire-json-unicode-svg-onload",
        module: Module::Xss,
        field: Field::JsonBody(r#"{"test": true, "7a756a623d": "\u0025\u0033\u0043\u0073\u0076\u0047\u0025\u0032\u0046\u0078\u003d\u0025\u0032\u0032\u0025\u0033\u0045\u0025\u0032\u0032\u0025\u0032\u0046\u006f\u004e\u006c\u006f\u0061\u0044\u003d\u0063\u006f\u006e\u0066\u0069\u0072\u006d\u0025\u0032\u0038\u0025\u0032\u0039\u0025\u0032\u0046\u0025\u0032\u0046"}"#),
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["xss-event-handler"],
        desc: "WIRE pcap L1220: JSON backslash-u svg/onload XSS — JSON leaf never canonicalized \
               (single percent-decode would catch it; serde unescape alone is not enough)",
    },
    // ── documented limits (need §6 HTML normalization — out of 10b rules-only) ───
    Case {
        id: "xss-mutation-tag-break",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "autof<x>ocus o<x>nfocus=alert<x>(1)//" },
        min_pl: 1,
        expect: Expect::ExpectedMiss { until_phase: None },
        rules: &[],
        desc: "mutation XSS: <x> inserted to break onfocus/alert tokens — needs §6 HTML tag-stripping",
    },
    Case {
        id: "xss-entity-obfuscated-scheme",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "<a href=javas&#99;ript:prompt&#x28;document.domain)>xss" },
        min_pl: 1,
        expect: Expect::ExpectedMiss { until_phase: None },
        rules: &[],
        desc: "HTML-entity-obfuscated javascript:/prompt( — needs §6 HTML-entity decoding",
    },
    // ── benign / traps ─────────────────────────────────────────────────────────
    Case {
        id: "xss-benign-javascript-prose",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "JavaScript: Basics of JavaScript Language" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "10b FP fix: 'javascript:' in prose (no call) must NOT match xss-javascript-proto",
    },
    Case {
        id: "xss-benign-confirm-prose",
        module: Module::Xss,
        field: Field::Query { name: "msg", value: "Please confirm (your order) and we will alert you" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "sink words in prose with a paren — must NOT match xss-js-sink-invocation (needs .call/.apply)",
    },
    Case {
        id: "xss-benign-alert-prose",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "the alert system (v2) notifies users" },
        min_pl: 2,
        expect: Expect::Clean,
        rules: &[],
        desc: "bare-sink trap: 'alert' + later paren but a space before '(' — must NOT match xss-js-sink-call",
    },
    Case {
        id: "xss-benign-document-bracket",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "document[\"title\"] = pageTitle" },
        min_pl: 2,
        expect: Expect::Clean,
        rules: &[],
        desc: "bracket access to a non-cookie property — must NOT match xss-document-cookie",
    },
    Case {
        id: "xss-benign-basic-markup",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "<b>bold</b> and <i>italic</i> text" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "harmless inline markup, no dangerous tags or handlers",
    },
    Case {
        id: "xss-trap-on-params",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "browse online and onsale items" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "event-handler narrowing trap: 'online'/'onsale' must not match on\\w+=",
    },
    Case {
        id: "xss-benign-plain-comment",
        module: Module::Xss,
        field: Field::Query { name: "comment", value: "Please respond by email soon" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "plain prose comment",
    },
];
