//! XSS corpus cases. Field coverage: query + cookies + body.
//! Rules (paranoia): script-tag 1, javascript-proto 1, event-handler 1,
//! dangerous-tag 2, eval 2, document-cookie 2, vbscript-proto 3, data-html-uri 3,
//! innerhtml 3.

use crate::{Case, Expect, Field, Module};

pub static CASES: &[Case] = &[
    // ── malicious: one per rule ────────────────────────────────────────────────
    Case {
        id: "xss-script-tag-query",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "<script>alert(1)</script>" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["xss-script-tag"],
        desc: "inline <script> tag",
    },
    Case {
        id: "xss-javascript-proto-query",
        module: Module::Xss,
        field: Field::Query { name: "url", value: "javascript:alert(document.domain)" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["xss-javascript-proto"],
        desc: "javascript: protocol handler",
    },
    Case {
        id: "xss-event-handler-query",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "<img src=x onerror=alert(1)>" },
        min_pl: 1,
        expect: Expect::Triggers,
        rules: &["xss-event-handler"],
        desc: "inline onerror event handler",
    },
    Case {
        id: "xss-dangerous-tag-query",
        module: Module::Xss,
        field: Field::Query { name: "html", value: "<iframe src=about:blank></iframe>" },
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["xss-dangerous-tag"],
        desc: "<iframe> dangerous tag (Warning/PL2)",
    },
    Case {
        id: "xss-eval-cookie",
        module: Module::Xss,
        field: Field::Cookie("pref=eval(atob('YWxlcnQ='))"),
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["xss-eval"],
        desc: "eval() call in a cookie value (Warning/PL2)",
    },
    Case {
        id: "xss-document-cookie-query",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "x=document.cookie" },
        min_pl: 2,
        expect: Expect::Triggers,
        rules: &["xss-document-cookie"],
        desc: "document.cookie access (Warning/PL2)",
    },
    Case {
        id: "xss-vbscript-proto-query",
        module: Module::Xss,
        field: Field::Query { name: "url", value: "vbscript:msgbox(1)" },
        min_pl: 3,
        expect: Expect::Triggers,
        rules: &["xss-vbscript-proto"],
        desc: "vbscript: protocol handler (Notice/PL3)",
    },
    Case {
        id: "xss-data-html-uri-query",
        module: Module::Xss,
        field: Field::Query { name: "src", value: "data:text/html,hello" },
        min_pl: 3,
        expect: Expect::Triggers,
        rules: &["xss-data-html-uri"],
        desc: "data:text/html URI (Notice/PL3); plain text payload to isolate the rule",
    },
    Case {
        id: "xss-innerhtml-query",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "el.innerHTML=payload" },
        min_pl: 3,
        expect: Expect::Triggers,
        rules: &["xss-innerhtml"],
        desc: "innerHTML sink assignment (Notice/PL3)",
    },
    // ── benign / traps ─────────────────────────────────────────────────────────
    Case {
        id: "xss-benign-basic-markup",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "<b>bold</b> and <i>italic</i> text" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "harmless inline markup, no dangerous tags or handlers",
    },
    Case {
        id: "xss-trap-on-params",
        module: Module::Xss,
        field: Field::Query { name: "q", value: "browse online and onsale items" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "event-handler narrowing trap: 'online'/'onsale' must not match on\\w+=",
    },
    Case {
        id: "xss-benign-plain-comment",
        module: Module::Xss,
        field: Field::Query { name: "comment", value: "Please respond by email soon" },
        min_pl: 1,
        expect: Expect::Clean,
        rules: &[],
        desc: "plain prose comment",
    },
];
